CREATE TABLE IF NOT EXISTS define_sheet_data (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  project_id VARCHAR(64) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  sheet_data LONGTEXT NOT NULL,
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_project_file (project_id, file_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
